repositoryUrl: https://github.com/dynamsoft-docs/camera-enhancer-docs-mobile/blob/main
repository: dynamsoft-docs/camera-enhancer-docs-mobile
docFullPath: https://www.dynamsoft.com/camera-enhancer/docs/mobile/
firstLevelUrl: /camera-enhancer/docs/core
docHomePage: /camera-enhancer/docs/core/introduction/
frontPageFolder: /camera-enhancer/docs/core/

productUrl: https://www.dynamsoft.com/camera-enhancer/overview/
productName: Dynamsoft Camera Enhancer

introduction: /camera-enhancer/docs/core/introduction/
programming: /camera-enhancer/docs/core/programming/
parameters: /camera-enhancer/docs/core/parameters/
license_activation: /camera-enhancer/docs/core/license-activation/
release_notes: /camera-enhancer/docs/core/release-notes/
parameter-reference: /camera-enhancer/docs/core/parameters/reference/
faq: /camera-enhancer/docs/core/faq/

ios: /camera-enhancer/docs/mobile/ios/
ios-guide: /camera-enhancer/docs/mobile/ios/guide/
ios-api: /camera-enhancer/docs/mobile/ios/primary-api/
ios-api-auxiliary: /camera-enhancer/docs/mobile/ios/auxiliary-api/
ios-release-note: /camera-enhancer/docs/mobile/ios/release-note/
ios-cameraenhancer: /camera-enhancer/docs/mobile/ios/api/cameraenhancer/

android: /camera-enhancer/docs/mobile/android/
android-guide: /camera-enhancer/docs/mobile/android/guide/
android-api: /camera-enhancer/docs/mobile/android/primary-api/
android-api-auxiliary: /camera-enhancer/docs/mobile/android/auxiliary-api/
android-release-note: /camera-enhancer/docs/mobile/android/release-note/
android-cameraenhancer: /camera-enhancer/docs/mobile/android/primary-api/cameraenhancer/

js: /camera-enhancer/docs/web/javascript/
js-guide: /camera-enhancer/docs/web/javascript/user-guide/
js-api: /camera-enhancer/docs/web/javascript/api-reference/
js-rn: /camera-enhancer/docs/web/javascript/release-note/

flutter: /capture-vision/docs/mobile/programming/flutter/
flutter_api: /capture-vision/docs/mobile/programming/flutter/api-reference/

xamarin: /capture-vision/docs/mobile/programming/xamarin/
xamarin_api: /capture-vision/docs/mobile/programming/xamarin/api-reference/

cordova: /capture-vision/docs/mobile/programming/cordova/
cordova_api: /capture-vision/docs/mobile/programming/cordova/api-reference/

react_native: /capture-vision/docs/mobile/programming/react-native/
react_native_api: /capture-vision/docs/mobile/programming/react-native/api-reference/

reference: /camera-enhancer/docs/core/parameters/reference/
enumerations: /camera-enhancer/docs/core/parameters/enumerations/
mobile-enum: /camera-enhancer/docs/core/programming/enumerations/

license-error: /camera-enhancer/docs/core/faq/license-error/
contact-us: /camera-enhancer/docs/core/faq/contact-us/
gallery: /camera-enhancer/docs/core/resources/code-gallery/
all-release-note: /camera-enhancer/docs/core/release-notes/
resource: /camera-enhancer/docs/core/resources/

barcode-deploy-ios: /barcode-reader/programming/ios/api-reference/camera-enhancer/
barcode-deploy-android: /barcode-reader/programming/android/api-reference/camera-enhancer/
barcode-enum: /barcode-reader/parameters/enum/

assets: /camera-enhancer/docs/core/assets/
edit_icon: /camera-enhancer/docs/core/assets/img-icon/edit-icon.png
smile_icon: /camera-enhancer/docs/core/assets/img-icon/icon-smile.png
sad_icon: /camera-enhancer/docs/core/assets/img-icon/icon-sad.png
dbr_icon: /camera-enhancer/docs/core/assets/img-icon/icon-dbr.svg
dwt_icon: /camera-enhancer/docs/core/assets/img-icon/icon-dwt.svg
dnt_icon: /camera-enhancer/docs/core/assets/img-icon/icon-dnt.svg

overview: /camera-enhancer/overview/
download: /camera-enhancer/downloads/1000021-confirmation/

useVersionTree: true

baseurl: "/camera-enhancer/docs/core/"
plugins:
  - jemoji
  - jekyll-sitemap
  
defaults:
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false
  - scope:
      path: "programming/javascript"
    values:
      category: "js-repo"
      edition: "js"
  - scope:
      path: "programming/android"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "programming/objectivec-swift"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "programming/flutter"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "programming/xamarin"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "programming/cordova"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "programming/react-native"
    values:
      category: "mobile-repo"
      edition: "mobile"

url: "https://www.dynamsoft.com" # sitemap root
